name: "Helm Dependencies Upgrader"
description: "GitHub Action to upgrade Helm dependencies on a Helm folder."

inputs:
  chart-path:
    description: "Path to the Helm chart folder."
    required: true
  readme-path:
    description: "Path to a README.adoc with AsciiDoc attributes in the format ':<DEPENDENCY_NAME>-chart-version: <DEPENDENCY_VERSION>' that will be updated in the event of an upgrade."
    required: false
    default: ""
  upgrade-strategy:
    description: "Upgrade strategy to use. Valid values are 'major', 'minor' or 'patch'."
    required: false
    default: "minor"
  excluded-dependencies:
    description: "Comma-separated list of dependencies to exclude from upgrade."
    required: false
    default: ""
  dry-run:
    description: "Run the action in dry-run mode to check possible upgrades but do not perform any upgrade."
    required: false
    default: "false"

outputs:
  is-updated:
    description: "Boolean indicating whether any dependencies were upgraded."
  is-major:
    description: "Boolean indicating at least one of the dependencies was subject to a major upgrade."

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.dry-run }}
    - ${{ inputs.readme-path }}
    - ${{ inputs.chart-path }}
    - ${{ inputs.upgrade-strategy }}
    - ${{ inputs.excluded-dependencies }}
